### ISSUE TITLE
Sonar Plugin is no longer working

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/google-cloud-spanner-hibernate#135]
Seems like the sonar plugin configuration is no longer working; see latest build: https://api.travis-ci.com/v3/job/248885402/log.txt

```
Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.1.1688:sonar (default-cli) on project google-cloud-spanner-hibernate: Not authorized. Please check the properties sonar.login and sonar.password.
```

@meltsufin - any ideas for what might be wrong?

**Comment by meltsufin** [comment]
I suspect that this section in the `.travis.yml` needs to be re-encrypted.
```
addons:
  sonarcloud:
    organization: "google-cloud-spanner-hibernate"
    token:
      secure: "pNSuPozHIh/W..."
```
